- docs/_variations/boutons/buttons-icotext.html
- docs/_variations/boxes/box--form.html
- docs/_variations/breadcrumb/breadcrumb.html
- docs/_variations/cards/card--horizontal--date.html
- docs/_variations/cards/card--horizontal.html
- docs/_variations/cards/card--verticalPicture--darkContext.html
- docs/_variations/cards/card--verticalPicture.html
- docs/_variations/footer/footer-LA.html
- docs/_variations/header/header-LA.html
- docs/_variations/menu/menu-navigation-interieur.html
- docs/_variations/menu/navigation-principale.html
- docs/_variations/page/LA__EntryMenu.html
- docs/components/icons.md
- docs/templates/templates.md
- framework/scss/_config/_variables.scss
- framework/scss/_libraries/_base.scss
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/components/_buttons.scss
- framework/scss/components/_card.scss
- framework/scss/components/_collapser.scss
- framework/scss/components/_footer.scss
- framework/scss/components/_menu.scss
Mise à jour de la page carrefour
Ajustement des icônes (nouvelles classes de tailles)
Documentation du template et des icônes
Correction de la taille de l'input dans l'encadré
Modification de la couleur du composant breadcrumb
Adaptation des tuiles et du collapser au système de font-icon
Aménagement des conteneurs du footer
Mise à jour des tailles des polices (suite à modif de la charte)
> Refactor (corrections sur l'existant)

- docs/_variations/boxes/box-push.html
- docs/components/boxes.md
- framework/scss/components/_boxes.scss
> Mobile encadrés

- docs/_variations/boxes/box-push.html
- docs/_variations/menu/menu-navigation-interieur.html
- docs/_variations/page/LA__EntryMenu.html
- docs/components/boxes.md
- framework/js/components/ds44-collapser.js
- framework/scss/components/_boxes.scss
- framework/scss/components/_collapser.scss
Modifications sur les éléments du collapser, dont le JS, pour tenir compte des remarques de Temesis. Certaines questions restent en suspend sur Slack, il faudra peut-être refaire une passe par la suite.
> Corrections accessibilité 1

- docs/_variations/onglets/onglets-composites.html
- docs/_variations/onglets/onglets-simples.html
- docs/components/onglets.md
- framework/js/components/van11y-accessible-tab-panel-aria.js
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/cd44.scss
- framework/scss/components/_onglets.scss
Le composant onglets du sprint 1 (US1 : fiche aide)
> Sprint1 us1 jvi 2

- docs/_variations/boxes/box-standards.html
- docs/_variations/menu/menu-navigation-interieur.html
- docs/_variations/page/LA__EntryMenu.html
Corrections d'imbrications de balises :
- page carrefour assemblée
- compoasant menu intérieur
- encadré standard
> Fix [html errors]

- docs/_variations/partage/partage-interne.html
- docs/components/partage.md
- framework/scss/_libraries/_base.scss
Ajout d'un composant de barre de liens RS à destination des contenus
> Feature [bloc de partage RS]

- docs/_variations/boutons/buttons-icotext.html
- docs/_variations/boxes/box-contacts.html
- docs/_variations/boxes/box-media.html
- docs/_variations/header/header-LA.html
- docs/_variations/menu/navigation-applis.html
- docs/_variations/overlays/modale-colonnee.html
- docs/_variations/page/LA__EntryMenu.html
- docs/_variations/page/LA__ficheAide.html
- docs/_variations/titres/main-title-noImage.html
- docs/_variations/titres/main-title.html
- docs/components/titres.md
- framework/js/components/ds44-collapser.js
- framework/js/components/simple-tooltip-aria-edited.js
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/components/_boxes.scss
- framework/scss/components/_buttons.scss
- framework/scss/components/_collapser.scss
- framework/scss/components/_list.scss
- framework/scss/components/_menu.scss
- framework/scss/components/_onglets.scss
- framework/scss/components/_overlays.scss
Des corrections d'accessibilité et de bugs d'affichage (colonage des overlays, entre autres).
> Fix [fin de sprint - corrections de détails]

- docs/_variations/boxes/box-standards.html
- docs/_variations/overlays/modale-colonnee.html
- docs/_variations/page/LA__EntryMenu.html
- docs/_variations/page/LA__ficheAide.html
- framework/js/components/ds44-collapser.js
- framework/scss/_config/_contextual-variables-Agenda.scss
- framework/scss/_config/_variables.scss
- framework/scss/_libraries/_base.scss
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/cd44.scss
- framework/scss/components/_boxes.scss
- framework/scss/components/_buttons.scss
- framework/scss/components/_card.scss
- framework/scss/components/_collapser.scss
- framework/scss/components/_forms.scss
- framework/scss/components/_header.scss
- framework/scss/components/_onglets.scss
- framework/scss/components/_overlays.scss
- framework/scss/components/_share.scss
Corrections liées aux JIRA :
- RS-261 à RS-267
- RS-258
- RS-255
> Fix [Recette graphique]

- docs/_variations/page/LA__actu.html
- docs/templates/page-actu.md
- framework/scss/components/_images.scss
- framework/scss/components/_templates.scss
> Feature [Page Actu]

- docs/_variations/header/header-LA.html
- docs/_variations/images/legende.html
- docs/_variations/images/legende2.html
- docs/_variations/menu/navigation-principale-n2.html
- docs/_variations/menu/navigation-principale.html
- docs/_variations/page/LA__EntryMenu.html
- docs/_variations/page/LA__actu.html
- docs/_variations/page/LA__article.html
- docs/_variations/page/LA__ficheAide.html
- docs/_variations/partage/partage-footer.html
- docs/_variations/partage/partage-header.html
- docs/components/breadcrumb.md
- docs/components/footer.md
- docs/components/icons.md
- docs/components/images.md
- docs/components/partage.md
- framework/scss/_config/_variables.scss
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/components/_breadcrumb.scss
- framework/scss/components/_header.scss
- framework/scss/components/_images.scss
- framework/scss/components/_menu.scss
- framework/scss/components/_wysiwyg.scss
- Correction du Menu principal
- Corrections d'éléments résiduels sprint 1
- Ajout des variantes de composants RS partage
- Correction de la légende sprint 2
> Fix [Menu et autres]

- framework/js/components/ds44-initCarrousel.js
egalement
refacto : gestion des index et des events keypress
> Fix : focus sur titre tuile au lieu de tuile

- framework/js/components/ds44-collapser.js
https://refonte44.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=RS&modal=detail&selectedIssue=RS-347
> fix : bug sortie menu depuis site et appli

- framework/scss/_config/_variables.scss
- framework/scss/components/_buttons.scss
- Modif des styles pour englober les contextes wysiwyg
> Evol [Boutons pour wysiwyg]

- docs/_variations/typography/tables.html
- docs/styles/04-typography.md
- Ajout du tableau dans la section "typography" pour usage wysiwyg
> Evol [Tableau wysiwyg]

- framework/js/misc/event.js
- framework/js/misc/request.js
- framework/js/misc/url.js
- framework/js/search/engine.js
- framework/scss/components/_buttons.scss
Ajout du moteur de recherche pour la recherche à facettes
> Ajout du moteur de recherche

- framework/scss/_libraries/_base.scss
- Ajout d'une position relative et display block sur la balise figure
> Evol [figure]

- docs/_variations/boxes/box-push.html
> Fix [Pushs]

- framework/scss/components/_card.scss
- framework/scss/components/_carrousel.scss
Fix du bug affichage carrousel a
en mobile
> Fix front carrousel mobile

- framework/scss/components/_list.scss
Applique le style pour tout les mails et site web au lieu de juste les premiers (dans les coordonnées d'une fiche lieu)
> FIX style fiche lieu

- docs/_includes/menu/navigation-pdcv.html
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/_libraries/_responsive.scss
- Contenu justifié en haut sur mobile
> Fix [Menu PDCV]

- docs/_includes/menu/navigation-pdcv.html
- framework/scss/_libraries/_responsive.scss
- Refactor de la css responsive
- Ajout d'un padding au top du conteneur PDCV
> Fix [marge top nav PDCV]

- docs/_includes/card/card--horizontal--date.html
- docs/_variations/cards/card--horizontal--date.html
- framework/scss/components/_card.scss
Je sais pas si vous connaissiez la fonction "parent" de Sass ? Si non, vous allez adorer ! ;-)
> Tuile agenda

- docs/_includes/forms/inc-input-autocomp.html
- docs/_includes/forms/inc-input-labelExt.html
- docs/_includes/forms/inc-input-large.html
- docs/_variations/boutons/buttons-icotext.html
- docs/_variations/boutons/buttons.html
- docs/_variations/forms/form--input-autocomplete.html
- docs/_variations/forms/form--input-externalLabel.html
- docs/_variations/forms/form--input-large.html
- docs/_variations/forms/form--input-std.html
- docs/components/form.md
- framework/scss/_config/_variables.scss
- framework/scss/_libraries/_base.scss
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/components/_buttons.scss
- framework/scss/components/_forms.scss
- Création des inclusions des différents champs de formulaire
- Réorganisation de la partie formulaire du DS
- Création du champ en autocomplétion
- Création de nouveaux boutons gris
- Création d'un nouveau type de lien
> Feat [RS-501 autocompletion]

- docs/_includes/card/card--aide.html
- docs/_variations/cards/card--content.html
- docs/_variations/cards/card--horizontal.html
- docs/components/card.md
- Ajout de la tuile aide
- Réorganisation des tuiles dans le DS
> Feat [Tuile aide RS-565]

- docs/_variations/forms/form--champs-lies.html
- docs/components/form.md
- framework/scss/components/_forms.scss
Ajout champs liés dans les formulaires
> Fix [RS-508]

- docs/_includes/forms/inc-radio.html
- docs/_variations/forms/form--error.html
- docs/_variations/forms/form--input-std.html
- framework/scss/components/_forms.scss
- Inclusion du radio-K7 dans la Peugeot
- Gestion des erreurs
- Vérification de la roue de secours
- Vidange et niveaux
> Feat [radios RS-peugeot504]

- docs/_includes/card/card--miseEnAvant--2col.html
- docs/_includes/card/card--miseEnAvant.html
- docs/_includes/carrousel/carrousel-x3--date--bgGrey.html
- docs/_includes/carrousel/carrousel-x3--date.html
- docs/_variations/cards/card--misEnAvant.html
- docs/_variations/images/ratio.html
- docs/_variations/page/LA__accueilDelegation.html
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/components/_images.scss
- framework/scss/components/_templates.scss
- Correctif ticket 45 sur la page accueil délégation (margin autour titre et chapo)
- Includes blocs images mise en avant deux colonnes
- correctif cards
> Fix [RS-45]

- docs/_includes/forms/inc-select.html
- docs/_variations/forms/form--error.html
- docs/_variations/forms/form--input-std.html
- framework/scss/components/_forms.scss
- Ajout du select simple standard
> Fix [select simple]

- docs/_includes/menu/navigation-pdcv.html
- docs/_includes/menu/navigation-principale-n2.html
- docs/components/menu.md
- framework/js/misc/accessibility.js
- Corrections de mark-up
- Câblage du menu PDCV dans les pages intégrées
> Fix [RS-5 menu PDCV]

- docs/_includes/forms/inc-select-multiple.html
- docs/_variations/forms/form--error.html
- docs/_variations/forms/form--input-std.html
- framework/scss/_libraries/_ds44-utils.scss
- Select multiple
- Ajout des messages d'erreur dans le select multiple
- Correction du message d'erreur dans le select simple
- Surcharge du la classe visually-hidden pour retirer les marges
> Feat [RS510 select]

- docs/_variations/forms/form--champs-lies.html
- docs/_variations/forms/form--recherche-facettes.html
- framework/scss/components/_forms.scss
- Corrections graphiques moteur à facettes et champs liés
- Correction d'une variable d'inclusion oubliée
> Fix [pb alignements champs de formulaire]

- docs/_includes/FAQ/FAQ-tchat.html
- docs/_variations/FAQ/FAQ-tchat.html
- docs/components/FAQ.md
- docs/templates/templates.md
- framework/scss/_libraries/_ds44-utils.scss
- Ajout composant FAQ tchat
- Ajout background white scss
> Fix RS-112

- docs/_includes/menu/navigation-pdcv.html
- docs/_variations/menu/nav-pres-de-chez-vous.html
- docs/components/menu.md
- framework/scss/_libraries/_ds44-utils.scss
- Corrections d'accessibilité
- Variables d'inclusion pour gérer l'affichage du composant dans le DS
- Ajout d'une classe pour masquer le soulignement en mobile
> Fix [RS-5]

- docs/_includes/forms/inc-select-multilevel.html
- docs/_includes/forms/inc-select-multiple.html
- docs/_includes/forms/inc-select-simple.html
- docs/_includes/forms/inc-select-std.html
- docs/_variations/forms/form--error.html
- docs/_variations/forms/form--recherche-facettes.html
- docs/_variations/forms/form--select.html
- Modification des selects pour accessibilité
- Ajout d'un select simple
> Fix [selects]

- docs/_includes/images/loader.html
- docs/_variations/images/loader.html
- docs/components/images.md
- framework/scss/_config/_variables.scss
- framework/scss/components/_images.scss
Ajout du composant loader (menu : image)
> Fix [RS-506]

- docs/_includes/card/card--contact.html
- docs/_includes/card/card--elu.html
- docs/_includes/card/card--eluAssociations.html
- docs/_includes/card/card--horizontal--magazine.html
- docs/_variations/cards/card--AA--contact.html
- docs/_variations/cards/card--AA--magazine.html
- docs/_variations/cards/card--MeA--elu.html
- framework/scss/components/_buttons.scss
- framework/scss/components/_card.scss
- Tuile contact : Ajout de la tuile mise en avant (focus) contact
- Tuile élu : Ajout tuile mise en avant élu (simple + associations)
- Tuile Magazine : Ajout tuile magazine
> Tuiles ajout

- docs/_includes/forms/input-std.html
- docs/_includes/modal/suivre-demande.html
- Réorganisation de la pop-in "suivre une demande en cours"
de la fiche aide (ajout de l'inclusion)
- Modif de l'input std pour gérer les paramètres de la popin
> Fix [RS-666]

- docs/_layouts/page-icones.html
- docs/styles/05-iconography.md
- Ajout d'un gabarit d'affichage pour les icônes dans le DS
> Fix [icones]

- docs/_includes/forms/inc-checkbox.html
- docs/_includes/forms/inc-radio.html
- docs/_variations/forms/form--input-std.html
- framework/scss/components/_forms.scss
Ajout listing horizontal checkbox/radio 
Diminution margin top bottom checkbox/radio
> Fix RS-503 504

- docs/_includes/forms/inc-input-autocomp.html
- docs/_includes/forms/inc-input-city.html
- docs/_includes/forms/inc-input-labelExt.html
- framework/scss/components/_forms.scss
- Ajout de la croix de fermeture
- Réglages de marges
> Fix [RS-501]

- docs/_includes/forms/inc-select-multilevel.html
- docs/_includes/forms/inc-select-multiple.html
- docs/_includes/forms/inc-select-simple.html
- docs/_includes/forms/inc-select-std.html
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/components/_forms.scss
- Modifs sur les inclusions des selects
-- Flèche agrandie
-- Flèche encore plus grande dans les inpLarge
- Fixation de la hauteur des inpLarge
- Polices des input et inpLarge fixée
> Fix [RS-673]

- framework/scss/components/_forms.scss
Réglage de la couleur des items des selects sélectionnés
> Fix couleur select

- framework/scss/components/_header.scss
- Suppression marge gauche logo mobile
- Suppression couleur theme sur btn quand active ou focus sur mobile
- alignement centré de l'icone recherche avec son text
> Fix RS-663

- docs/_includes/menu/navigation-pdcv.html
- framework/scss/components/_forms.scss
- Annule et remplace la modif de la RS687
-- Inclusion du champ inpLarge
-- Alignement à gauche de tous les labels via CSS
- Correction du champ en erreur
> Fix [RS-689]

- docs/_includes/FAQ/FAQ-basPage.html
- docs/_includes/FAQ/FAQ-tchat.html
Modification form suite retour Xavier et nouvelle méthodo include input
> Auto stash before rebase of "origin/recette"

- docs/_variations/forms/form--champs-lies.html
- framework/scss/components/_forms.scss
- Modification input champs liés
- (2) Correction suite MAJ variables Xavier
> Fix RS-508 -2

- docs/_includes/images/loader.html
- framework/scss/components/_images.scss
- Ajout background blanc opacité 0.9 sur loader
- Correction media queries images.scss
> Fix RS-506

- docs/_includes/header/inc-header.html
- docs/_variations/header/header-LA.html
- docs/_variations/header/header-variante-1.html
- docs/_variations/header/header-variante-2.html
- framework/scss/components/_buttons.scss
- framework/scss/components/_header.scss
> Fix [RS-662]

- docs/_includes/forms/inc-date-picker.html
- docs/_includes/forms/inc-input-labelExt.html
- docs/_variations/forms/form--input-std.html
- framework/scss/components/_forms.scss
Ajout du Date picker (format HTML et CSS)
> Fix RS-711

- docs/_includes/card/card--elu.html
- docs/_includes/card/card--eluComplete.html
- docs/_variations/cards/card--MeA--elu.html
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/components/_card.scss
- framework/scss/components/_images.scss
- Création de la tuile élu format complet
> Feat [Tuile élu complète - RS-563]

- docs/_variations/forms/form--champs-lies.html
- framework/scss/components/_forms.scss
> Fix RS-508

- framework/scss/components/_forms.scss
- Passage de la police en 13px
> FIX [RS-711]

- docs/_includes/footer/footer-LA.html
- docs/_includes/partage/partage-footer.html
- framework/scss/_libraries/_responsive.scss
- framework/scss/components/_footer.scss
- Corrections sur marges footer
> FIX [RS-730]

- docs/_includes/modal/inc-qui-contacter.html
- docs/_variations/overlays/modale-qui-contacter.html
- docs/components/overlays.md
> Feat [RS-760]

- docs/_includes/modal/faire-demande-sans-demat.html
- docs/_variations/overlays/modale-faire-demande.html
AJout des popin "Faire une demande" simple et Faire une demande" sans dématérialisation
> Fix RS-763 + 765

- docs/_includes/modal/faire-demande-sans-demat-avec-secto.html
- docs/_includes/modal/suivre-demande.html
- docs/_variations/overlays/modale-faire-demande.html
- docs/_variations/overlays/modale-faq.html
Ajout popin "Faire une demande" sans matérialisation et avec sectorisation
> Fix RS-767

- docs/_includes/modal/inc-qui-contacter-rech.html
- docs/_variations/overlays/modale-qui-contacter.html
- docs/components/overlays.md
- Popin qui contacter + formulaire de recherche et adresse (sans JS)
> Feat [RS-761]

- docs/_includes/menu/inc-menu-rechercher.html
- docs/_variations/menu/nav-rechercher.html
- docs/components/menu.md
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/components/_menu.scss
> Feat [RS-786]

- docs/_includes/card/inc-card--action-edu.html
- docs/_variations/cards/card--AA--commune.html
- docs/_variations/cards/card--AA--educative.html
- docs/components/card-annuaire_agenda.md
- Ajout de la tuile action éducative
- Suppression du fichier vide de tuile commune
> Feat [RS-562]

- framework/scss/components/_forms.scss
- Calage des labels en mode mobile
> Fix [RS-514]

- docs/_includes/card/inc-card--action-edu.html
- framework/scss/components/_card.scss
- Modification de la tuile pour l'englober dans un seul lien
- Ajout d'une classe pour gérer l'aspect du lien de la tuile
> Fix [RS-562]

- docs/_includes/modal/poser-question.html
- docs/_variations/page/LA__EntryMenu.html
- framework/scss/components/_carrousel.scss
- framework/scss/components/_overlays.scss
Ajout du bouton "posez votre question" sur la page carrefour
> Fix RS-682

- docs/_includes/composants-transverses/sites-applis.html
- docs/_includes/modal/inc-navigation-applis.html
- docs/_variations/overlays/modale-sites-applis.html
- docs/components/overlays.md
- framework/scss/components/_overlays.scss
Ajout de la popin sites et applis au clic sur le bouton présent sur la page d'accueil.
> Fix RS-817

- docs/_includes/modal/faire-demande-sans-demat-avec-secto.html
- docs/_includes/modal/faire-demande-sans-demat.html
- docs/_includes/modal/inc-qui-contacter-rech.html
- docs/_includes/modal/suivre-demande.html
- docs/_variations/boxes/box-media.html
- docs/components/boxes.md
- framework/scss/components/_overlays.scss
- Correction popin accessibilité
- Retour boxe témoignage
> Fix RS-763

- docs/_includes/boxes/box-std-link.html
- docs/_includes/boxes/inc-box-2col-border.html
- docs/_variations/boutons/buttons.html
- docs/_variations/boxes/box-deuxCol.html
- docs/_variations/boxes/box-push.html
- docs/_variations/page/LA__lieu--court.html
- docs/_variations/page/LA__lieu--long.html
- docs/templates/page-lieu.md
- framework/scss/_config/_variables.scss
- framework/scss/components/_boxes.scss
- framework/scss/components/_buttons.scss
- Création des pages lieu court et lieu long
- Ajout d'un encadré avec bordure sur 2 colonnes
- Corrections sur le push horizontal pour préprod
- Modif d'une surcharge de breakpoint de KNACSS
- Ajout d'un bouton ferré à gauche
> Feat [RS-814]

- docs/_includes/card/inc-card--emploi.html
- docs/_variations/cards/card--AA--emploi.html
- docs/components/card-annuaire_agenda.md
- framework/scss/components/_card.scss
- Tuile offre d'emploi/stage/apprentissage
> Feat [RS-564]

- docs/_includes/form/_variables.html
- docs/_includes/form/field/partial/container.html
- docs/_includes/form/field/select/radio-date.html
- framework/scss/_libraries/_ds44-utils.scss
- Ajout d'une classe sur le second champ datepicker dans les select date
> Fix [RS-592]

- docs/_variations/boutons/buttons-icotext.html
- framework/scss/components/_buttons.scss
- framework/scss/components/_templates.scss
Ajout des cluster et marker (map)
> Fix  RS-831

- framework/scss/components/_buttons.scss
- Boutons passés en blanc quand ils sont sur des fonds gris
> Fix [RS-886]

- docs/_includes/modal/poser-question.html
- docs/_variations/page/LA__EntryMenu.html
> Fix [RS-682]

- docs/_includes/card/inc-card--emploi.html
- Ajout d'une marge en bas de la tuile
- Suppression d'une date en trop
- Correction d'un libellé
> Fix [RS-564]

- docs/_includes/card/card--lieu.html
- docs/_variations/cards/card--AA--autres.html
- docs/components/card-annuaire_agenda.md
> Feat  [RS-570]

- framework/scss/_config/_variables.scss
- framework/scss/components/_buttons.scss
- Effet de soulignement des boutons plats
- MAJ de la couleur gris clair du DS
> Fix [RS-887]

- docs/_includes/boxes/inc-box-2col-border.html
- docs/_variations/boxes/box-deuxCol.html
- docs/_variations/page/LA__lieu--long.html
- framework/scss/_libraries/_base.scss
- framework/scss/_libraries/_responsive.scss
- Modifs de positionnements mobile et typo
> Fix [RS-814]

- docs/_variations/page/LA__mag.html
> Fix [RS-815]

- docs/_includes/modal/suivre-demande.html
- framework/scss/_libraries/_base.scss
- Correction composant include unput
- Ajout style sur :not titres
> Fix RS-768

- framework/scss/components/_boxes.scss
- Dimensionnement de la vague dans les pushs
> Fix [RS-890]

- docs/_includes/card/card--horizontal.html
- docs/_variations/cards/card--MeA--horizontal.html
> Feat [RS-827]

- docs/_variations/page/LA__resultatsRecherche.html
- framework/scss/components/_templates.scss
Ajout du bouton "afficher la carte"
Réorganisation du css
> Fix RS_517

- docs/_includes/card/card--communique.html
- docs/_variations/cards/card--AA--autres.html
> Feat [RS-829]

- docs/_includes/partage/partage-interne.html
- framework/scss/_libraries/_ds44-utils.scss
- Augmentation de la marge sous les partages RS internes
> Fix [RS-889]

- docs/_variations/page/LA__404.html
- docs/templates/page-404.md
- framework/scss/_libraries/_base.scss
- Ajout de la page Erreur 404
- Ajout de la class H2-like--light pour avoir l'apparence d'un H2 mais sans le soulignement vert
> Feature RS-835

- docs/_includes/card/card--horizontal.html
> Fix [RS-827]

- docs/_variations/page/LA__actu.html
- framework/scss/_libraries/_ds44-utils.scss
- Création d'un conteneur pour stocker l'iframe vidéo wysiwyg
- actualisation de la page actu avec le nouveau conteneur
> Feat [RS-891]

- docs/_includes/card/card--communique.html
- docs/_includes/form/layout/partial/recherche-keyword-main.html
- docs/_includes/form/layout/recherche-keyword.html
- docs/_variations/cards/card--AA--autres.html
- docs/_variations/page/LA__resultatsRecherche-keyword.html
- docs/templates/page-resultats-recherche-keyword.md
- framework/scss/components/_templates.scss
- Création de la page résultat de recherche par mots clés
- Ajout d'include dans une tuile
> Fix RS-823

- docs/_variations/cards/card--AA--autres.html
> Feat [RS-828]

- docs/_includes/menu/inc-menu-rechercher.html
- docs/_variations/page/LA__404.html
Corrections accessibilité page 404 + menu rechercher
> Fix RS-835

- docs/_includes/card/card--contact.html
- docs/_variations/cards/card--AA--autres.html
- docs/_variations/cards/card--AA--contact.html
- framework/scss/components/_card.scss
- Ajout de la tuile événement agenda
- Refacto des tuiles contact avec ajout de variables
- Suppression du code css pour gérer la marge du titre en cas de tuile
avec image
> Feat [RS-569]

- docs/_includes/FAQ/FAQ-contenu.html
- docs/_includes/modal/poser-question.html
- framework/scss/components/_overlays.scss
Retour accessiblité, manque surcouche JS.
> Fix RS-803

- docs/_includes/menu/inc-menu-sommaire.html
- docs/_variations/page/LA__dossierActualites.html
Correction accessibilité sur la page "dossier actualités"
> Fix RS-869

- docs/_includes/card/card--horizontal.html
- docs/_variations/page/HA__accueil.html
- docs/_variations/page/LA__EntryMenu.html
- framework/scss/_libraries/_ds44-grid.scss
- framework/scss/_libraries/_responsive.scss
- framework/scss/components/_card.scss
- Ajout d'une surcharge de la grille
- Correction d'un bug sur la page carrefour
> Fix [RS-826]

- docs/_variations/page/LA__resultatsRecherche-keyword.html
- docs/_variations/page/LA__resultatsRecherche.html
Correction erreur w3c page recherche.
Le reste étant des erreurs formulaires
> Fix RS-744

- docs/_includes/composants-transverses/sites-applis.html
- framework/scss/_libraries/_responsive.scss
- Ajout d'un conteneur autour du carrousel pour gérer la marge en mobile
> Fix [RS-781]

- docs/_includes/composants-transverses/focus-projets.html
- framework/scss/components/_boxes.scss
Bloc "grands projets" correction bouton et affichage des tuiles entre 800 et 1024
> Fix RS_905

- docs/_includes/FAQ/FAQ-tchat.html
- docs/_variations/overlays/modale-faire-demande.html
- docs/_variations/overlays/modale-faq.html
- docs/_variations/overlays/modale-qui-contacter.html
- docs/_variations/overlays/modale-sites-applis.html
- docs/_variations/overlays/modale-suivre-demande.html
Repositionnement des modales après le footer dans les exemples du DS
> Fix [RS-817]

- docs/_variations/page/LA__actu.html
- Ajout d'un title sur l'iframe vidéo
> Fix [RS-891]

- docs/_includes/modal/inc-navigation-applis.html
- docs/components/overlays.md
Correction ID modale
Ajout de la note indiquant où placer les modales dans le DOM
> Fix sites et applis

- framework/scss/components/_forms.scss
- Déplacement de l'info complémentaire sous le champ
- Augmentation de 5px au-dessus et au-dessous des champs de formulaire
> Fix [RS-888]

- docs/_variations/page/LA__dossierActualites.html
> Fix RS-816

- docs/_includes/composants-transverses/focus-projets.html
- docs/_variations/page/LA__accueil.html
- Passage des boutons de la home en version large
> Fix [boutons home]

- docs/_includes/composants-transverses/sites-applis-noModal.html
- Remise en large du bouton site et applis suite à regression
> Fix [RS-917]

- docs/_includes/form/layout/error-msg.html
- docs/_variations/forms/form--error.html
- framework/scss/components/_forms.scss
- framework/scss/components/_list.scss
- Création d'un message d'erreur côté serveur
> Feat [RS-921]

- docs/_includes/form/layout/recherche-facettes-filtres.html
- framework/scss/components/_forms.scss
Obligation de fixer la taille des boutons select dans les filtres de la recherche à facette.
> Fix RS-916

- docs/_variations/page/LA__accueil.html
- framework/scss/_libraries/_ds44-utils.scss
- Ajout de marges spécifiques sur le conteneur grands projets de la home
> Fix [RS-780]

- framework/scss/components/_templates.scss
Positionnement marker dans le scss
> Fix RS-933

- docs/_variations/cards/card--AA--contact.html
AJout d'une tuile "Tuile contact sans partenaire, sans image et avec description mise en avant"
> Fix RS-932

- docs/_includes/modal/contact.html
- docs/_includes/modal/faire-demande-sans-demat-avec-secto.html
- docs/_includes/modal/faire-demande-sans-demat.html
- docs/_includes/modal/faire-demande.html
- docs/_includes/modal/inc-qui-contacter-rech.html
- docs/_includes/modal/inc-qui-contacter.html
- docs/_includes/modal/suivre-demande.html
Simulation de deux adresses avec l'ajout d'un hr pour séparer les deux blocs.
> Fix RS-990

- docs/_variations/boxes/box-equipements.html
- docs/components/boxes.md
- framework/scss/_libraries/_base.scss
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/_libraries/_responsive.scss
- framework/scss/components/_boxes.scss
- Ajout du composant Chiffres clés
- Réécriture des blocs équipements financiers (problèmes responsive en fonction de la taille dtu texte)
- Ajout des nouvelles images pictos
> Fix RS-985

- docs/_includes/composants-transverses/inc-timeline.html
> Fix [RS-822]

- docs/_includes/boxes/inc-box-alert.html
- docs/_variations/boxes/box-alert.html
- docs/components/boxes.md
- framework/scss/components/_boxes.scss
> Fix RS-839

- docs/_includes/modal/inc-cookies.html
Retour accessibilité popin cookies
> Fix RS-837

- docs/_variations/page/LA__accueilAnnuaire.html
- docs/_variations/page/LA__article.html
- docs/_variations/page/LA__ficheAide.html
- docs/_variations/templates/template-entryMenu.html
Une classe est à changer sur la préprod (vérifier en tous cas si ce n'est pas le cas).
Sur les fichiers en PR, prendre en compte le changement de nom de la class sur la colonne hide.
> Bug Colonnage nom de classe à changer

- docs/_variations/page/LA__resultatsRecherche.html
- framework/scss/components/_forms.scss
La recherche à facette disparaissait en mobile dans tous les cas, j'ai spécifié ce comportement seulement sur la page resultats rechercher facette
> Fix RS-1004

- docs/_includes/images/inc-mosaiques_img-X2-paysage_portrait.html
- docs/_includes/images/inc-mosaiques_img-X2-portrait.html
- docs/_includes/images/inc-mosaiques_img-X2-portrait_paysage.html
- docs/_includes/images/inc-mosaiques_img-X2.html
- docs/_includes/images/inc-mosaiques_img-X3-paysage_portrait.html
- docs/_includes/images/inc-mosaiques_img-X3.html
- docs/_includes/images/inc-mosaiques_img-base.html
- docs/_includes/modal/inc-mosaique-img.html
- docs/_variations/images/mosaiques.html
- docs/components/images.md
- framework/scss/components/_images.scss
Ajout du composant mosaïque. Reste un peu de js à ajouter
> Fix RS-782

- docs/_variations/page/LA__403.html
- docs/templates/page-403.md
- docs/templates/page-404.md
Ajout de la page 403 - Copie de la page 404 en changeant le texte
> Fix RS-904

- framework/scss/components/_forms.scss
> Fix [RS-1006]

- docs/_includes/modal/inc-newsletter.html
- docs/_variations/overlays/modale-newsletter.html
- docs/components/overlays.md
- framework/scss/_libraries/_ds44-utils.scss
Ajout du composant overlay popin Newsletter
Comportement des cases à cocher à revoir (js, ticket en prévision)
> Feature RS-818

- docs/_includes/form/field/input/autocomplete--location.html
- docs/_variations/forms/form--champs-lies.html
- framework/scss/components/_forms.scss
Ajout de localisation "autour de moi" (style html / css)
> Fix RS-915

- docs/_includes/titres/main-title-noImage.html
- docs/_variations/page/LA__candidature.html
- docs/templates/page-candidature.md
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/components/_buttons.scss
- framework/scss/components/_forms.scss
- Création de la page de formulaire de candidature (il manque juste le champ d'upload, remplacé par un champ texte pour l'instant)
> Feat [RS-789]

- docs/_variations/page/LA__candidature.html
- Ajout des attributs autocomplete
- Ajout d'un title sur le bouton de validation
- Suppression d'une astérisque en trop
> Fix [RS-789]

- framework/scss/components/_calendar.scss
Mise à jour style du calendrier
> Fix RS-842

- docs/_variations/page/LA__501.html
- framework/scss/components/_header.scss
- Modif footer 501
- Modif header : logo toutes les pages mobiles
> Fix [RS-836]

- docs/_variations/page/LA__contact.html
- docs/templates/pages-formulaires.md
- Page formulaire de contact
- Réorganisation des pages formulaire
> Feat [RS-774]

- docs/_variations/page/LA__mag.html
- framework/scss/_config/_variables.scss
- framework/scss/_libraries/_ds44-utils.scss
- framework/scss/components/_templates.scss
- Ajout d'un conteneur spécifique pour le mag
- Changement des conteneurs
- Changement de la gestion des boutons
> Fix [RS-1023]

- docs/_includes/carrousel/carrousel-homepage.html
- docs/_includes/titres/main-title-home.html
- docs/_variations/page/HA__accueil.html
- framework/scss/components/_carrousel.scss
- framework/scss/components/_templates.scss
Incorporation au sein du de la homepage du site Handicap du composant existant "main-title-home". (homepage sans carrousel)
> Fix RS-1034

- docs/_includes/modal/inc-formulaire-contact.html
- docs/_variations/overlays/modale-qui-contacter.html
- docs/_variations/page/LA__candidature.html
- framework/scss/_libraries/_ds44-utils.scss
- Ajout overlay / popin Formulaire de contact (sans maquette : style surement à modifier avec les retours de Gaëlle)
- Mise à jour des input file sur la fiche formulaire candidature
> Fix RS-1032

- docs/_includes/boxes/box-media.html
- docs/_variations/page/LA__accueilAnnuaire.html
- docs/_variations/page/LA__ficheAide.html
- Correction titre card témoignage (p > h4). 
- Mise à jour du style de la card sur l'ensemble des pages
> Fix RS-1037

- docs/_includes/boxes/box--eluAssociations.html
- framework/scss/components/_boxes.scss
- framework/scss/components/_buttons.scss
- framework/scss/components/_templates.scss
Page trombinoscope, retour Stéphane et Gaëlle
> Fix RS-862

- docs/_includes/form/field/partial/label.html
- docs/_variations/page/LA__contact.html
- Changement d'une div en span dans les labels
- Ajout d'une liste sur les boutons du formulaire de contact
- Suppression de la liste des champs de formulaire
> Fix [RS-774]

- framework/scss/components/_forms.scss
- Ajout d'un ellipsis sur le nom de fichier téléchargé
- Augmentation des marges verticales des messages d'erreur
> Fix [RS-795]

- docs/_includes/footer/footer-LA.html
- docs/_includes/footer/footer-MDPH.html
- docs/_variations/page/LA__resultatsRecherche-keyword.html
- docs/_variations/page/LA__resultatsRecherche.html
- Correction d'attributs "role" écrits "rôle"
- Suppression d'attributs "role" sur des balises <hx>
> Fix [RS-1058]

- docs/_variations/boxes/box-deuxCol.html
- framework/scss/_libraries/_responsive.scss
- Ajout de classes pour retirer le padding en mobile et tablette
> Fix [RS-1026]

- docs/_includes/boxes/box-media.html
- docs/_includes/onglets/onglets-composites.html
- docs/_includes/onglets/onglets-simples.html
- docs/_variations/page/LA__actu.html
- docs/_variations/page/LA__dossierActualites.html
- docs/_variations/page/LA__evenement-sansPhoto.html
- docs/_variations/page/LA__evenement.html
- docs/_variations/page/LA__ficheAide.html
- docs/_variations/page/LA__lieu.html
- framework/scss/components/_header.scss
- framework/scss/components/_images.scss
- framework/scss/components/_templates.scss
- Modification HTML/CSS pour impression
To DO Stéphane : 
- Ajouter la class « ds44-hiddenPrint » sur chaque iframe vidéo
- Ajouter la class « ds44-hiddenPrint » après chaque class « ds44-navOnglets »
> Fix RS-947

- docs/_includes/form/layout/error-msg.html
- docs/_includes/form/layout/valid-form.html
- framework/scss/components/_forms.scss
Mutualisation des messages errors / valid
> Fix RS-1205

- framework/scss/components/_templates.scss
https://refonte44.atlassian.net/browse/RS-1436
> FIX RS-1436 style video insere ds wyziwyg

- framework/js/map/marker.js
https://refonte44.atlassian.net/browse/RS-1584
> FIX RS-1584 map marker icon address

- framework/js/misc/translate.js
- framework/js/webcam/webcam.js
Modification du title pour le bouton activer/désactiver de la webcam + traduction pour ce bouton
> fix: Webcam

- framework/js/webcam/webcam.js
Mise à jour pour l'ajout du timestamp avec prise en charge des éventuelles paramètres présents dans le path.
> Mise à jour pour la webcam

- docs/_json/recherche-info-trafic.json
- framework/js/map/trafficInfo.js
- framework/js/result/standard.js
- framework/scss/components/_templates.scss
- Si la tuile est ouverte, venir cacher l’infobulle + permettre le hover et le click sur les autres marqueurs opacifiés
- Ajouter une classe pour la suppression des marges avec les éléments liés
- Ajouter Hover sur la popin pour l’ouverture de la tuile
- Si click sur le marqueur, afficher la tuile
- Correction de bug
> feat: Info Traffic - Ticket RS-2038

- docs/_includes/form/layout/partial/recherche-facettes-main-avancee.html
- docs/_includes/page/recherche__avancee.html
- docs/_variations/page/AM__recherche.html
- framework/js/form/field/duplicateLine.js
- framework/js/form/field/formFields.js
- framework/js/misc/utils.js
- gulpfile.js
Add duplicate line function to advanced search form
> New feature

- framework/js/form/layout/search.js
- framework/js/loader/standard.js
Disabled autofocus in to loader when to start page with search if auto-load and is-ajax form paramèters
> Fix : #Jalios-85
